version: '3.7'

services:
  config-server:
    image: store-config-service
    build:
      context: .
      dockerfile: ./store-config-service/Dockerfile
    ports:
      - 8888:8888
    restart: always
    networks:
      - spring-cloud-network

  eureka-server:
    image: store-eureka-service
    build:
      context: .
      dockerfile: ./store-eureka-service/Dockerfile
    ports:
      - 9091:9091
    restart: always
    depends_on:
      - config-server
    networks:
      - spring-cloud-network

  auth-server:
      image: store-auth-service
      build:
        context: .
        dockerfile: ./store-auth-service/Dockerfile
      ports:
        - 9092:9092
      restart: always
      depends_on:
        - config-server
        - eureka-server
        - auth-db
      networks:
        - spring-cloud-network

  auth-db:
      image: postgres:latest
      ports:
        - "5432:5432"
      restart: always
      environment:
        POSTGRES_DB: auth
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      networks:
        - auth-network


networks:
    spring-cloud-network:
        driver: bridge
    auth-network:
         driver: bridge