version: '3.7'

services:
  config-server:
    image: store-config-service
    build:
      context: .
      dockerfile: ./store-config-service/Dockerfile
    ports:
      - 8888:8888
    restart: always
    networks:
      - spring-cloud-network

  eureka-server:
    image: store-eureka-service
    build:
      context: .
      dockerfile: ./store-eureka-service/Dockerfile
    ports:
      - 9091:9091
    restart: always
    depends_on:
      - config-server
    networks:
      - spring-cloud-network

networks:
    spring-cloud-network:
        driver: bridge